### ISSUE TITLE
Error: {"message":"Invalid request.\n\nFor 'links/0/schema', \"body\" is not an object.

### ISSUE THREAD

**Issue by BugCommiter** [kgryte/github-create-issue#6]
Hello, I have a error with types. However, when I used typeof() to check type of variable all alright (My variable is string )

Type of Image: string

{ limit: 5000, remaining: 4993, reset: 1628201207 }
Error: {"message":"Invalid request.\n\nFor 'links/0/schema', \"body\" is not an object.","documentation_url":"https://docs.github.com/rest/reference/issues#create-an-issue"}
    at clbk (D:\Github desktop\GMC_adminBot\src\commands\bug.js:105:19)
    at done (D:\Github desktop\GMC_adminBot\node_modules\github-create-issue\lib\create.js:72:3)
    at done (D:\Github desktop\GMC_adminBot\node_modules\github-create-issue\lib\query.js:65:11)
    at onError (D:\Github desktop\GMC_adminBot\node_modules\github-create-issue\lib\request.js:61:10)
    at IncomingMessage.onEnd (D:\Github desktop\GMC_adminBot\node_modules\github-create-issue\lib\request.js:107:11)
    at IncomingMessage.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[ERROR] 00:27:06 Error: {"message":"Invalid request.\n\nFor 'links/0/schema', \"body\" is not an object.","documentation_url":"https://docs.github.com/rest/reference/issues#create-an-issue"}
[INFO] 00:27:25 Restarting: D:\Github desktop\GMC_adminBot\src\commands\bug.js has been modified

**Comment by kgryte** [comment]
Hey, thanks for filing an issue. I'm going to need more info in order to figure out what is going wrong. How are you calling the API and with what arguments?

**Comment by BugCommiter** [comment]
![изображение_2021-08-06_211418](https://user-images.githubusercontent.com/88492355/128554324-503af48b-510f-4f48-a044-31b6d66140be.png)

**Comment by BugCommiter** [comment]
Error appear if this condition is true
![image](https://user-images.githubusercontent.com/88492355/128554534-5c51c208-ee9b-43a8-a7ce-93e675f8443b.png)

**Comment by kgryte** [comment]
You may have some luck examining the log output when running the CLI with the `DEBUG` environment variable set (as shown [here](https://github.com/kgryte/github-create-issue#examples-1)).

I think what may be happening is that the `Content-Length` header is not being [computed](https://github.com/kgryte/github-create-issue/blob/40612361f618ac0d0b52b23f641d78ca6342b19a/lib/query.js#L37) correctly.

In a [port](https://github.com/stdlib-js/stdlib/blob/142156faef6856871ff1cf13f96dd3ee939d428a/lib/node_modules/%40stdlib/_tools/github/create-issue/lib/query.js#L60) we use in `stdlib`, we compute the byte length, rather than the string length.

If you wouldn't mind testing locally to confirm that modifying how the `Content-Length` header is set resolves the issue and submitting a PR, that would be greatly appreciated!

Thanks!

**Comment by BugCommiter** [comment]
What should i do?

**Comment by kgryte** [comment]
You can try changing the line which sets the `Content-Length` header to first convert the serialized request `data` to a Node.js `Buffer` and then set the `Content-Length` header to the `byteLength` of the `Buffer`.

**Comment by BugCommiter** [comment]
Deleting this string was fixed my error
![image](https://user-images.githubusercontent.com/88492355/128610892-17abd297-491e-46b6-9009-654126793ca4.png)

**Comment by kgryte** [comment]
Yeah, that should work, as well.
